(global-set-key (kbd "C-=") 'er/expand-region)
(global-set-key (kbd "C-s") 'swiper)
(global-set-key (kbd "C-S-s") 'choug/swiper-dwim)
(global-set-key (kbd "C-M-s") 'spacemacs/helm-project-do-rg)
(global-set-key (kbd "C-;") 'iedit-mode)
(global-set-key (kbd "<C-backspace>") 'choug/backward-delete-word-or-region)
(global-set-key (kbd "M-DEL") 'choug/backward-delete-word-or-region)
(global-unset-key (kbd "C-t"))
(global-set-key (kbd "C-}") 'centaur-tabs-forward)
(global-set-key (kbd "C-{") 'centaur-tabs-backward)
(global-set-key (kbd "M-m i e") 'tiny-expand)
