(global-set-key (kbd "C-=") 'er/expand-region)
(global-set-key (kbd "C-s") 'swiper)
(global-set-key (kbd "C-S-s") 'choug/swiper-dwim)
(global-set-key (kbd "C-M-s") 'helm-projectile-ag)
(global-set-key (kbd "C-;") 'iedit-mode)
